pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Hi') {
            steps {
                echo 'Hi everyone!!!'
            }
        }
         stage('Pipeline job') {
            steps {
                echo 'Sandra first pipeline'
            }
        }
        stage('Docker') {
            steps {
                echo 'Sandra first docker command'
            }
        }

        stage('kubernetes') {
            steps {
                echo 'this is kubernetes session'
            }
    
        }
    
    
        stage('github action') {
            steps {
                echo 'github action is  lovely'
            }
        }

        stage('final') {
            steps {
                checkout changelog: false, poll: false, scm: scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github-connect', url: 'https://github.com/Sandraolis/jenkins-scm.git']])
                echo "${env.BUILD_URL}"
            }
        }
    }


}
