pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Hi') {
            steps {
                echo 'Hi everyone!!!'
            }
        }
         stage('Pipeline job') {
            steps {
                echo 'Sandra first pipeline'
            }
        }
        stage('Docker') {
            steps {
                echo 'Sandra first docker command'
            }
        }

        stage('kubernetes') {
            steps {
                echo 'this is kubernetes session'
            }
        }
    }
}